Repository tetele/onju-voice-satellite, pull requests merged in 2024-04, with the labels that each got.

#29 Add friendly name to config
  esphome/onju-voice-microwakeword.yaml
  esphome/onju-voice.yaml
Labels: bugfix

#32 Display volume if changed externally
  esphome/onju-voice.yaml
Labels: new-feature

#33 Stop media when enabling WW
  esphome/onju-voice.yaml
Labels: bugfix

#36 bugfix: on_end race condition / Speaker buffer full
  esphome/onju-voice-microwakeword.yaml
Labels: bugfix

#37 Add PSRAM module to onju-voice.yaml
  esphome/onju-voice.yaml
Labels: new-feature

#38 bugfix: fix typos in esphome friendly_name variable
  esphome/onju-voice-microwakeword.yaml
  esphome/onju-voice.yaml
Labels: bugfix

#40 refactor: remove redundant build_flag for PSRAM
  esphome/onju-voice-microwakeword.yaml
  esphome/onju-voice.yaml
Labels: refactor
